import { FaHeart, FaStar, FaUpload } from 'react-icons/fa';
import { TbSlideshow } from 'react-icons/tb';

export const levels = [
  {
    id: 1,
    name: 'Level 1',
    path: 'level-1',
    color: 'Aprenderás el vocabulario y el contenido temático de la misión',
    isRegistered: false,
    buttonsData: [
      {
        size: 'medium',
        enabled: true,
        animate: true,
        status: "COMPLETED",
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'white',
        urlFrame: 'https://view.genially.com/669d9ffca0c4cb116db1cfd2',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'white',
        urlFrame: 'https://view.genially.com/66a1c49d51ad4fd5ce765fdc',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'white',
        urlFrame: 'https://view.genially.com/669848c9c8257f39138d79d3',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        icon: 'TbSlideshow',
        iconColor: 'white',
        backgroundColor: 'purple-500',
        borderColor: 'pink-500',
        urlFrame: 'https://view.genially.com/66a047d5aa29150a6708c477',
      },
    ],
  },
  {
    id: 2,
    name: 'Level 2',
    path: 'level-2',

    color: 'Contiene lecciones interactivas, lecturas y ejercicios prácticos',

    isRegistered: true,
    buttonsData: [
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'blue-500',
        urlFrame: 'https://view.genially.com/669732380e7954656cb23148',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'blue-500',
        urlFrame: 'https://view.genially.com/6695a58f4f58be1862202742',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'blue-500',
        urlFrame: 'https://view.genially.com/66a1c4d451ad4fd5ce767d16',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        icon: 'FaStar',
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'blue-500',
        urlFrame: 'https://view.genially.com/669848c9c8257f39138d79d3',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'blue-500',
        urlFrame: 'https://app.nearpod.com/?pin=K52MN&he=true',
      },
      {
        size: 'medium',
        enabled: true,
        animate: true,
        iconColor: 'white',
        backgroundColor: 'green-500',
        borderColor: 'blue-500',
        urlFrame: 'https://view.genially.com/66a68c03e0c64b0109444408',
      },
    ],
  },
  {
    id: 3,
    name: 'Level 3',
    path: 'level-3',
    color: 'Crearas un producto que evidencie tu aprendizaje a lo largo de la misión.',
    isRegistered: false,
    exercises: [],
    buttonsData: [
      {
        size: 'medium',
        enabled: true,
        animate: true,
        icon: 'FaUpload',
        iconColor: 'white',
        backgroundColor: 'blue-500',
        borderColor: 'blue-500',
        urlFrame: '',
      },
    ],
  },
];
